### ISSUE TITLE
node.js:201 error in Ubuntu 1204

### ISSUE THREAD

**Issue by ghost** [wwidd/wwidd#9]
$ ./start.sh

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:378:11)
    at Object.<anonymous> (/home/magnus/Wwidd/server/src/server.js:5:8)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:41)

**Comment by danstocker** [comment]
The 0.4.6 release requires node 0.4.x. I will push a fix to the stable branch that would make it work with node 0.8.x.

**Comment by ghost** [comment]
Thank you.

**Comment by danstocker** [comment]
Hi! You can now download a 0.4.7 snapshot (or pull from the 'stable' branch) which supports Node 0.8.x.

**Comment by AllesMeins** [comment]
I had the same problem as ghost (Ubuntu 12.04 as well). Using the stable branch fixes this issue, but unfortunatly causes another problem. The wwidd server won't start with the following error:

$ ./start.sh 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'tools/browser'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/gedinixan/wwidd/wwidd/server/src/server.js:8:13)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)

I did some digging in the code. If I change "browser = require('tools/browser').browser" to "browser = require('./tools/browser').browser" in server.js this error goes away and it complains about not finding "tools/ifconfig". I can change this as well and it pops up with the next module that could not be found. So this seems to be a general problem with the search path. Is there anything you can do about it?

**Comment by danstocker** [comment]
Hi,
I'm about to get my hands on a Ubuntu 12.04 soon, but I've been getting similar errors in OS X Lion (Node 0.8) too. I just pushed a fix for OS X, you could try to use that and start Wwidd from under /server/src instead of /. (Like this: "node server.js debug") I'll get back to you when the Ubuntu test/fix is ready.

**Comment by AllesMeins** [comment]
Thanks for the update, but i've still troubles to get it to work. Now it is the module "flock-0.1.3" that cannot be found. I can fix it by copying flock-0.1.3.js from "common/flock" to "server/src" but than wwidd dies with

$ node server.js 
SYSTEM - OS type: linux
DB - switching over to DB: default

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'existsSync'
    at Object.exists (/tmp/wwidd/server/src/tools/sqlite.js:83:18)
    at Object.name (/tmp/wwidd/server/src/db/db.js:50:16)
    at /tmp/wwidd/server/src/db/db.js:79:7
    at Object.<anonymous> (/tmp/wwidd/server/src/db/db.js:82:2)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)

I guess it is best that I wait for your "official" ubuntu fix ;)

**Comment by danstocker** [comment]
Hi,
There were a few minor things to fix, those were committed, and now you'll find a step-by-step howto in the Wiki on a clean install. Let me know if you're still experiencing problems.

**Comment by bunder** [comment]
Trying to run git master gives me following error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '../../../common/flock/flock-0.1.5'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/bunder/src/arch/aur/wwidd/src/wwidd/server/src/utils/system.js:9:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

I'm using Archlinux x86_64 with nodejs 0.8.15.
